### ISSUE TITLE
Missing json annotation file

### ISSUE THREAD

**Issue by SimoLoca** [hanielwang/Refining_Boundary_Head#1]
Hi, thanks for your great work!
I cannot found the file "epic_kitchens_100_verb_plus_noun_700.json" for training the model with the script provided.
Am i missing anything?

Looking forward for your reply.

**Comment by SimoLoca** [comment]
@hanielwang

**Comment by hanielwang** [comment]
Hi, sorry for the delay reply. Actually it's a combined json file of verb and noun annotations. You can generate it by youself based on the annotation repository of EPIC-KITCHENS-100, I also provided the json file generated by myself, it could be found in annotations/. Pleases let me know if you have further questions, thanks.
